### ISSUE TITLE
Bug Report - 6.X.X series of versions crashes upon boot.

### ISSUE THREAD

**Issue by Hacksawfred3232** [FlagBrew/PKSM#1012]
**Describe the bug**
6.2.1 crashes upon boot. To confirm that this is not a duplicate of issue 826 and 831, no DS card inserted (Flashcart or game cart) still results in a crash.

**Steps to reproduce the behaviour**
1. Download and install version 6.2.1. 3DSX and CIA are both affected
2. Attempt to open the application.

**Expected behaviour**
App should open normally.

**Exhibited behaviour** 
Upon opening the application, it goes straight to a black screen for about 10-20 seconds and then either crashes out to the HB menu, or to the home screen depending on what the file format of the application was.

**Information about your environment**
 - 3DS Model: N3DS
 - OS version: System settings reports Sys 11.10.0-43E. 
 - PKSM version: 6.2.1
 - CFW: Luma 9.1 (With plugin loader patch).
   NOTE: Plugin loader was confirmed to be disabled when loading PKSM via its CIA version.
 - Bootloader: Boot9strap
 - HB Menu version: Rosalina 2.0.0
 - Entrypoint: SodokuHax/Seedminer (Installed using this [guide](https://3ds.hacks.guide/seedminer))

**Additional context**
When this has been posted, I will begin to attempt downgrading the version until PKSM boots correctly. Will update this issue when a working version has been established. 

**UPDATE 1:**
5.1.4 (Recorded working version in issue 831.): Works correctly. Safe version established.
6.0.0: ARM 11 Exception (See screenshot 1.)
6.0.1: Crashes
6.1.0: Crashes
6.1.1: Crashes
6.2.0: ARM 11 Exception (See screenshot 2 & 3.)
Screenshot 1:
![IMG_20190622_215948](https://user-images.githubusercontent.com/16674456/59968964-e7234180-953a-11e9-885a-575809fbeac7.jpg)
Screenshot 2:
![IMG_20190622_221155](https://user-images.githubusercontent.com/16674456/59968965-ed192280-953a-11e9-964b-ecc53eed537b.jpg)
Screenshot 3:
![IMG_20190622_221159](https://user-images.githubusercontent.com/16674456/59968968-f1ddd680-953a-11e9-9c0b-15b4dfde3deb.jpg)

Title has been updated in relation to this discovery.

**Comment by GriffinG1** [comment]
Do not downgrade again. That’s guaranteed to cause issues

**Comment by Hacksawfred3232** [comment]
I don't think you got the point. None of the 6.X.X versions work on my 3DS. Therefore, i am using 5.1.4 in the mean time. Please don't jump to conclusions.

**Comment by GriffinG1** [comment]
I am not. PKSM is not designed to downgrade. Period. You caused further issues downgrading back instead of just being patient and waiting for someone to help you.

**Comment by GriffinG1** [comment]
Reinstall 6.2.1 then go and clear your extdata for PKSM through FBI. If that doesn't work, then *wait*.

**Comment by Hacksawfred3232** [comment]
1. Downgrading breaks stuff? That's a bit dumb, But if that is really the case, that could explain why people are getting confused out of their minds when PKSM does not work for them. Why the hell did you not program in a catch block that handles EXT save wiping if it can't load due to the EXT save data being invalid? Or is it too low level? Oh and i am not asking you by the way. You are not working on this project anymore. Besides which, i don't think you can, Mister "Discord bot maker". So let the people at FlagBrew handle this. 
2. Doing what you just suggested has fixed the problem. Again however, let the people at FlagBrew handle this next time. 
*Note for the FlagBrew team btw: Why was this not mentioned in some sort of troubleshooting FAQ? It should be written down somewhere. Non Tech-savvy people do use this software!*
3. Caused further issues!? Dude, it was already broken in the first place. How could i cause more issues if it was already broken?

You clearly have no idea what you are doing here. You are clearly out of the league. And not forgetting to mention your rudeness and your desire to control everything that you don't own and fixing things that ain't broke (or blaming people for problems that they did not cause) You are not listed as a contributor here, and you have no moderator status here either. You really only can make Discord bots, judging from your Github account. I am getting Github's moderation team involved due to your despicable behaviour. And the "Racist" or "Homophobic" excuse won't work here, Mister Griffin.
Oh and to the FlagBrew team (@piepie62 , @FM1337, @BernardoGiordano), if he is really on your payroll or whatever, deal with him. His attitude here really proves that he is not up to the task. Otherwise, i think you know what to do with trespassers like him. This is absolutely unacceptable!

**Comment by piepie62** [comment]
Alright, Señor Arrogance, let's get to business. First, right now I, one of the most active PKSM contributors, am away from my computer earning actual money that allows me to continue even working on this project. Second, of *course* downgrading breaks stuff; when you upgrade, you can add special handling, and all attempts I have made to add special handling for downgrading have failed drastically for some unknown reason. Also, if you can't detect the ExtData being corrupt without a crash, how the hell are you supposed to wipe it? Not to mention ExtData being incorrect (not corrupt) can be cause by users, who would be quite mad if their entire bank was wiped because of a broken config file.

**Comment by Mike007899** [comment]
I noticed you closed this issue and I wanna clear some things up.

1, Downgrading anything will always break it, its common sense. The extdata is loaded upon boot for config and bank purposes.
2, That has always been the solution to fix it if it didnt work post v6.
3, You did cause further issues by downgrading and all you did.

There was no reason for this attack on them when all they did was give you instructions based on what you posted.

Good day.

**Comment by piepie62** [comment]
Wiping ExtData has never fixed a problem before  to my knowledge, so why *would* we include that in any FAQ? There's no way we would have known that was the issue, and if I remember correctly, when Bernardo tried to adrr2line your issue, he came up with picoc being the problem, a piece of code entirely unrelated to ExtData. While Griffin is not a part of the FlagBrew team, he is fairly experienced in troubleshooting our applications and a respected member of our community. We all get sassy from time to time when people do exactly what we tell them not to, and while in this case Bernardo did say that you were currently ising 5.1.4 because of weird issues, he said that to the FlagBrew team and not Griffin. I would appreciate it if you would not insult people without full context

**Comment by FM1337** [comment]
Dear @Hacksawfred3232,

With all due respect, while Griffin is not a part of the Flagbrew team, he is a rather important member of the Flagbrew community as well as a patron, stating something like "You really only can make Discord bots" is very disrespectful and honestly he's done more to help this community then you could expect.

I'm not going to dwell much seeing as you've already been given the gist by the other people, but I will say this, if you **EVER** want any assistance with any of Flagbrew's apps again, I expect an apology to be given to not only Griffin for your rude & snide remarks, but also an apology to be given to the Flagbrew team for your very repulsive unprofessional behavior.

Otherwise, do not ever ask for help again, as you will not receive it.

I believe I have made myself clear.

Thank you & have a wonderful day

Sincerely,
Allen, FM1337, FMCore

**Comment by Hacksawfred3232** [comment]
Oh for crying out loud. Let me make this very clear: Github is a **PROFESSIONAL** environment. Therefore, the behaviour Griffin exhibited is not acceptable. Professionalism first, sass second! If you want to have all that kind of "sass", go and get yourself GOGS and host a server somewhere. Its not that hard. Trust me, i know because i have one for my private projects. Mainly Python, trying to learn C++. 
2nd of all, Wiping ExtData fixed my problem. And i am pretty sure i never had PKSM installed to begin with. So what the hell was blaming me for!?
3rdly, going back to Github being a professional environment, I want to make something very clear: **THIS** is the **SECOND** time i had to deal with idiots pretending to be experts. Or in both cases, idiots who are experts but never help the people who are trying to get to that place and instead try to insult and provoke them. Par example, a guy on "Stack-Overflow"'s chat system who insulted me for using GCC instead of MSVC. i was having trouble with the library files that MSVC and GCC uses. Instead of going simply "Sorry bud, .lib files don't work with GCC, you need .a files. Should be pretty simple to compile them." (Which in fact, it is.), he decided to insult me, because he said i was making my life 10x harder for myself and called me an idiot. When in reality, dealing with MSVC was giving me headaches, and GCC was way more my style. Professionalism gets shit done. Sass only makes people angry and mad and gets nowhere.

You are not getting an apology from me, because Griffin is in fact in the wrong here. He should have stayed professional, and dealt with this, professionally. Instead of his snarky responses, he could have gone "Unfortunately, downgrading breaks some things. Please refrain from doing it". And he could have explained why it does break some things. In fact, Griffin should be the one apologising to me! Don't turn a blind eye to what is essentially his fault for provoking me. Otherwise, you will be making the same mistake the moderators on Stack-Overflow did. Antagonising the victim just because they reacted. 

Reconsider what you just said, @FM1337. Otherwise, expect to hear from Github's moderation team soon. I had enough of this messing around. I don't give any care about what he has done for a community if he is a disrespectful individual to other people outside of his community. 

Good day!

**Comment by FM1337** [comment]
@Hacksawfred3232 you have made it abundantly clear, that you can not act professionally or politely.

You will never receive any help from the flagbrew team or its community again.

I wish you luck in your future endeavours, as I have very little hope that you will ever be able to function in a professional environment
