### ISSUE TITLE
pksm bank file disconnect?

### ISSUE THREAD

**Issue by bloggingninja** [FlagBrew/PKSM#1036]
I have a japanese emunand and a US sysnand. normally I use PKSM to transfer pokemon from my japanese pokemon games to my english ones since pksm on the different nands would use the same bank file. today I updated PKSM to the latest version (6.2.1) and the emunand connected to the bank file fine, but the sysnand created a new bank file and now no longer shown any pokemon in storage. The storage is still accessible in the emunand. any Idea how to fix this? a google search gave me nothing.

**Comment by piepie62** [comment]
PKSM now uses ExtData to store the bank by default. There's a setting available to move the bank to the SD card instead of using ExtData, but I would highly recommend waiting for the next version to do that, as doing it right now may result in strange syncing issues if your settings aren't perfectly synced (and no, there's no way to move your configuration out of ExtData). For now, you can use Checkpoint to backup and restore your PKSM ExtData between your emuNAND and sysNAND; once the update comes out, I'd be happy to walk you through the process of moving your bank to the SD card. Sorry for the inconvenience this may have caused; I never thought about that use case

**Comment by piepie62** [comment]
Has been fixed in the Discord. Anybody facing the same issue should update to the latest version, then set the "Use ExtData" option in the configuration of the empty bank NAND to "No", then do the same for the full bank, in order to make sure that the full bank overwrites the empty bank. Updating to latest is mandatory because of possible bank size desyncs on <7.0.0
