### ISSUE TITLE
Bug Report - Extremely poor documentation

### ISSUE THREAD

**Issue by uehlbran** [FlagBrew/PKSM#1076]
This is pretty straight forward. Your documentation is so bad that I cannot find a single source on how anything in it actually works. Here's an example. I launch the application, select a save file, click wireless, and now everything is frozen. I tried to follow this guide to inject a wondercard: https://github.com/zaksabeast/PKSMBrowserInject but since your documentation is so bad I don't even actually know how to do it. so instead of being able to look on this page I'm having to rely on multiple 3rd party resources that don't work!

How about you take the 5 minutes I know you have and write a freaking guide!!!!!!!!!!!!!!!!!!!

**Comment by piepie62** [comment]
How about you stop being entitled? The wireless button clearly says it will lock the 3DS until a save is received, and that application is nowhere stated to be supported by us. It (and other similar applications) are not compatible with the latest release, and was not developed by us, so why are you complaining to us instead of its creator?
