### ISSUE TITLE
Bug Report - The app is stuck in loading screen

### ISSUE THREAD

**Issue by NAYIR55DevIndie** [FlagBrew/PKSM#1086]
**Describe the bug**
As the title says, when I open the app it get stucked in loading screen, nothing happen 

**To Reproduce**
1. I just opened the app several times and nothing happen

**Expected behavior**
I was expecting the app to work normally

**Screenshots**
![IMG_20191202_141245](https://user-images.githubusercontent.com/50130051/69992460-5308cd80-150f-11ea-925c-fea0bc1bdf9e.jpg)

**Information about your environment**
 - OS version: 11.12.0-44U
 - PKSM version: PKSM 7.0.1: Whoopsie
 - Entrypoint: I tried using the .cia and the .3dsx, and it is the same

**Additional context**
I was using the app normally 2 days ago, now it is broken for me

**Comment by GriffinG1** [comment]
@piepie62 was trying to help you in the discord server. Please don't just ignore someone trying to help you and instead go off to ask somewhere else.

**Comment by NAYIR55DevIndie** [comment]
Why all the dev communities are the same?
I KNOW I did read the message, and I did what he wrote in 2 lines but it didn't work...
And... I'm not asking for help somewhere else... i'm HERE reporting the bug to reach the developers and make them aware of this
Thanks

**Comment by GriffinG1** [comment]
Except it is not a bug. The app takes time to launch. It takes more time either due to asset downloads, or due to the number of automatic backups that PKSM makes. If you'd said in the server "it still isn't loading", you would've had further help to solve it. But instead you decided to open an issue here, making assistance slower and more annoying. 

Anyways, my guess is you've force closed the app while on that screen, the first time because you were impatient. This would've led to it corrupting one or more files pksm needs to load, as you closed the app while it was writing. And of course, we can probably fix it, but you'd have had it fixed two hours ago if you'd just responded on the server.
