### ISSUE TITLE
Wrong encounter for italian REGIGIGAS

### ISSUE THREAD

**Issue by Surax98** [FlagBrew/PKSM#1141]
Just change the REGIGIGAS obtaining place from "Lovely Place" to "Pokemon Event". I did it from PKHeX, but it sounds good to me to give you this advice. I forget to mention that i'm talking about 4th gen event

**Comment by piepie62** [comment]
PKSM does not handle constructing Pokémon from Wonder Cards. That means that either PKHeX gets it wrong *or* the wonder card itself is not proper, neither of which can be fixed by us. The two places you'd want to look are [PKHeX's repo](https://github.com/kwsch/PKHeX) or where we get all of the events, [EventsGallery's repo](https://github.com/projectpokemon/EventsGallery).
