### ISSUE TITLE
Make the main Open window newb friendly.

### ISSUE THREAD

**Issue by Galenmacil** [FlagBrew/PKSM#1208]
**Is your feature request related to a problem? Please describe.**
As a newcomer to PKSM, I have to admit I had a hard time getting started with it, mainly because most of the saves from GEN 3 to GEN 5 I have are coming from emulators/flashcard. The "Wireless" button that appears just under the "Load (A)" button is rather cryptic and the instructions on how to use it on the WIKI are even more so (for a neophyte...) It took me quite a while, after doing a few google search about "PKSM wireless instructions" to realize that, buried within the settings there is an option, named "Extra Saves" that allow to do just what I wanted.

**Describe the solution you'd like**
I think, it would be better to have the initial "Load" Window look something like this:

![game-select](https://user-images.githubusercontent.com/19394274/87242419-7e835d00-c3fa-11ea-82b8-4752ffe11c60.png)

That "Import..." button could then point you toward either "Import from a save file" or "Import via Wireless".

**Additional context**
Also, while being a little strange to me initially, I did manage to figure out what "Press Y for Absent Games" was doing. I understand that the focus was put on loading a save directly from a cartridge or from an installed Pokémon game on the 3DS SD Card but in my opinion, the save loading procedure would benefit from a bit of streamlining particularly for players like me who played the older games on emulators.

**Comment by piepie62** [comment]
There's a technical reason you have to go through the configuration menu to edit extra saves: PKSM has to scan through all of the possible saves and add them to a map, which is the reason that exiting the configuration screen can take a bit of time. I can't have configuration of extra saves outside of the configuration menu because of that. That would make the import button single-use for a given save, which would be a source of user frustration. Changing the main menu to integrate the Absent Games screen also reflects an architectural problem: I can't show icons of games that aren't there, as I grab the icons at runtime, and using my created icons would be *very* messy.
Furthermore, the wireless button is explained quite well. It's meant for users who either know what they're doing (and as such can use `netcat`) or using Switch Checkpoint, with instructions on how to actually use both Checkpoint and PKSM together [here](https://github.com/FlagBrew/PKSM/wiki/Basics#loading-a-save-over-a-network).
Overall, I appreciate the suggestion, but I just don't see a way that I can do that in any sane way, either user-facing or backend-wise.
