### ISSUE TITLE
when will zacian be in pksm

### ISSUE THREAD

**Issue by imalitt** [FlagBrew/PKSM#1246]
can you add zacian in in next update pls or is there another way to get him in pksm

**Comment by piepie62** [comment]
I will never add a way to create Gen 8 Pokémon in Gen 7 or lower games.

**Comment by Dom13377** [comment]
> I will never add a way to create Gen 8 Pokémon in Gen 7 or lower games.

Why is this may I ask? It would be useful to create these pokemon in USUM, then trasfer to bank and home, and then transfer to sword and shield to avoid CFW on the nintendo switch. The project is open source though, so maybe I will mess around with it if you neglect this idea. Thanks for your work.

**Comment by GriffinG1** [comment]
You cannot do that anymore regardless. Pie’s reasoning, I assume, is because it would produce grossly illegal Pokémon, as well as put the project at larger risk of a takedown from Nintendo.

**Comment by piepie62** [comment]
Griffin is essentially correct, though I don't personally think there would be a larger risk of takedown because of that. Overall there's no real utility to that "feature," and it explicitly goes against one of the main ideas that went into PKSM-Core's design goals, being limiting Pokémon and items to those that are available in that game
