### ISSUE TITLE
Bug Report - Impossible Item TM

### ISSUE THREAD

**Issue by sapfel93** [FlagBrew/PKSM#1247]
**Describe the bug**
When I try to send a Pokemon between a gen 3 game holding specific TMs (in this case, TM50, TM36, TM40), it won't allow me. It says "Impossible item" and refuses, even though those TMs are in Gen 3.

**To Reproduce**
1. Add a Pokemon from a Gen 3 game holding one of those TMs from your VC game to your storage.
2. Try to move that Pokemon from your storage to another gen 3 VC game.

**Expected behavior**
The Pokemon will be transferred back to the VC game.

**Screenshots**

**Information about your environment**
 - OS version: 3DS
 - PKSM version: 9.2.0-656eb68a
 - Entrypoint: CIA with Luma3DS

**Comment by Omega207** [comment]
I looked it up; for Gen 3. to Gen 7., TM50 is Overheat, but prior to Gen. 3 they are Substitute and Nightmare. Maybe it's because PKSM's trying to specify the right TM? In Gen. 8, it's Bullet Seed. I may be wrong, but you can transfer items from Gen. 8, if not at least Pokémon (from my perspective, the cloud storage). It may be the same in advance for Bullet Seed.

**Comment by GriffinG1** [comment]
Resolved in latest commits

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
