### ISSUE TITLE
Bug Report - Pokemon change gender upon transfer to gen 4 and 5 games

### ISSUE THREAD

**Issue by Trainerbluetube** [FlagBrew/PKSM#1252]
**Describe the bug**
I transferred my Glaceon back from Ultra Moon to Soul Silver, the nature changed from Hardy to Jolly and she turned into a he. I decided to transfer her to Black 2 and set her specifically back to female, twice, but when I opened the game, she was still male. When I went back to pksm, it said that she already was female.

**To Reproduce**
1. Go to 'Ultra Moon'
2. Transfer a female pokemon to the storage box, and then transfer it to a gen 4 game.
3. The nature and gender should change.

**Expected behavior**
I expected nothing to change upon transferring my Glaceon back. I wanted to take her back to Kanto and Johto since she's my favorite pokemon.

**Information about your environment**
 - OS version: 
 - PKSM version: 9.2.0
 - Entrypoint:

**Additional context**
The issue resolved on Black 2 after saving the file on pksm twice before opening the game.

**Comment by SpiredMoth** [comment]
Different generations store different values in the Pokémon data, and have different rules regarding some of those values.

In your case you're encountering the fact that gender and nature are not stored explicitly in the data in older generations but rather calculated from another value. Gender is calculated from the PID ([personality value](https://bulbapedia.bulbagarden.net/wiki/Personality_value)) in Generations 3-5 and the nature is calculated from the PID in Generations 3-4. Anything originating from later games has a chance to have traits of certain values with a PID that won't produce the same values.

PKSM keeps the values that are actually stored in the data unchanged during transfers as best it can. The changes you're seeing are because of this behavior.

**Comment by Trainerbluetube** [comment]
I see, but what about the bug/fix in gen 5? Do you know why the gender change took a few tries there?
