### ISSUE TITLE
Booting leads to a crash

### ISSUE THREAD

**Issue by RiceRun** [FlagBrew/PKSM#1277]
I load into pksm, it checks for updates and then crashes
I have the latest version of everything I need to load it so, why is it crashing?
I'm on a N3dsXL Luma 10.2.1 PKSM 9.2.0
![16223123322955416392952497815210](https://user-images.githubusercontent.com/79293290/120080927-cf538100-c0b2-11eb-9df3-3bb2cda913db.jpg)

**Comment by sergioinfosec** [comment]
Hello, how are you today, my friend?

I need one information about your console. So, to help me help you, please, do these steps:

- Power Off console
- Press select button + power button together 
- Take a picture of the next screen, it's your Luma configs (don't worry)
- Press START to leave that screen
- Post the picture here

What we will do? We will check your config to see more about that error. Often, fixing some options can make that screen never happen again.

See you around

**Comment by piepie62** [comment]
Do not listen to the person above; their fix is almost certainly a bad one that will cause more harm than good. That said, I can't do anything about this right now; I have unfortunately lost my copy of the ELF from the last release. This means I cannot use crash dumps to help me figure out where things are going wrong. After the next release, if this is still occurring, please open another issue and upload the actual crash dump (which you can save by pressing A) rather than a picture of that screen.
