### ISSUE TITLE
Bug Report - Memory Allocation Crash

### ISSUE THREAD

**Issue by ThisNekoGuy** [FlagBrew/PKSM#1280]
**Describe the bug**

Spending some time in the event menu, after have put the 3DS in sleep mode, then adding a list of events eventially caused a memory allocation error

Not sure why this happened :/

**To Reproduce**
1. Go to PKSM
2. Click on PKSM
3. Open the cartridge loaded (Omega Ruby)
4. Open the event menu
5. Select an event to add
6. Put the 3DS in sleep mode (perhaps even several times)
7. Navigate the menus for maybe 15 to 20 minutes(?), adding what you want
8. Memery error upon viewing an event
9. The 3DS locks up for a few minutes after the error occurs

**Expected behavior**

PKSM wasn't supposed to run out of memory

**Information about your environment**
 - OS version: Sys 11.14.0-46U
 - PKSM version: v9.2.0-656eb68a
 - Entrypoint: SIGHAX

**Comment by piepie62** [comment]
I'm pretty sure that I noticed and fixed this semi-recently for the next version. If not, I'm not really sure what would cause this except possible memory fragmentation over time, which I have no idea how to fix. I'm going to mark this as fixed for now because of my first sentence here, but if it's still an issue whenever I get around to releasing the next version, feel free to reopen it (as I'll close it on release)

**Comment by Omega207** [comment]
I've had a similar issue #1310 that I do not believe has been fixed. However, instead of putting the 3DS in sleep mode, this happens when I scroll through Wondercards. This only works for Gen. 7, and shows error `std::bad_alloc`.
I mention this because I'm curious if it's relating to my own issue.

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
