### ISSUE TITLE
Injector.c script does not inject wc3 files.

### ISSUE THREAD

**Issue by KeeveeKoomoo** [FlagBrew/PKSM#1289]
I was trying to inject event wonder cards into my pokemon emerald save, but the event section simply tells me to use the script "Injector.c". I did so after putting all of the gen 3 event files (including the e-reader files just to see what would happen) and when selecting an event from the list, it says I am using an invalid extension. If this is the case, what is the correct extension, and how would I go about converting the current files I own, to the correct extension?

**Comment by piepie62** [comment]
First, this is technically a script issue, so after I reply I'll be moving this issue over there.

Second, and more along the lines of what you wanted in an answer: WC3 is a made-up format that only PKHeX uses: real games do not. All Pokémon-distributing events were put directly into boxes without a "wonder card" format, and all Key Items were put directly into bags, also without a "wonder card". Given that event Pokémon are all available as PK3s, and that Key Items are handled separately, I, the person who wrote that script and updated it for G3, do not support WC3 as a format. There exists an event script that will give you the Key Items (and set proper flags, if they're required), though I cannot currently remember whether that's bundled in a PKSM release, in the script repository, or only in our Discord right now. If it's in the script repository, it'll be bundled in for the next release, if it's only in the Discord, whoever built it should PR it to the script repository so that that will happen. Unless somebody *really* wants to write WC3 parsing and stick it in the injector script (which, for the record, I'm not opposed to, I just don't want WC3 support inside of PKSM's Pokémon-format handling library itself), that will remain the case.
