### ISSUE TITLE
I think pksm may have broken my 3ds

### ISSUE THREAD

**Issue by KeeveeKoomoo** [FlagBrew/PKSM#1291]
I am not sure how, but I was using pksm on my pokemon white save file after I had been playing it all day. When I went to return to playing the game, it turns out, my 3ds had lost all ds functionality. Everything was working fine before this so I have no idea. I am really lost for ideas so I wanted to know if anybody else has come across this issue when using pksm or ever at all. Also, twlfix didn't work (yes I updated my 3ds afterwards) and neither does booting without the sd. Ds Internet settings also doesn't work. But ye my 3ds turns off whenever I try to use anything ds related and I can't find help elsewhere and I don't have access to discord. Only reason i am here was because the last thing I did before my 3ds broke was use pksm.

**Comment by Masamune3210** [comment]
well, I'll let you know right now that it wasn't this that caused anything. there is literally no way for it to, as to what's going on what happens if you try to boot with a clean SD card or no SD card

**Comment by KeeveeKoomoo** [comment]
ye I tries without the sd card but ds internert still didn't work :(

**Comment by Mewthree3** [comment]
Do you have a NAND backup on hand? I think that NAND backups cover the DS stuff too, so if you’ve made one, you should give it a shot, and try restoring it with GodMode9.
(This is slightly unrelated but I feel your pain with not having discord access. Makes troubleshooting ten times worse lol)

**Comment by KeeveeKoomoo** [comment]
I do have godmode9 but I have no idea how to use it so, I don't know how to
make or restore nand backups :(

**Comment by piepie62** [comment]
This literally cannot be PKSM-related. It doesn't touch anything related to that firmware mode

**Comment by KeeveeKoomoo** [comment]
Like I said only reason I'm here is cuz last thing I did before it broke
was use pksm

**Comment by Mewthree3** [comment]
So you said that you used TWLfix right? In that case, could you try using it once more, and then boot to recovery mode instead of updating?
Recovery mode is accessed after you power on the 3DS and hold the button combo of L+R+dpad up+A.
I have no idea if this could help but it’s worth a shot!



Also, I should teach you how to use GM9’s NAND backup feature because NAND backups are super important! NAND backups are like 1.2GB in size btw.
So boot into GM9, then press the 3DS’s home button.
From there go to Scripts… to GM9Megascript. You’ll be in a menu when you click that, and when you’re there, go to Backup Options, and click SysNAND Backup. Then press A, and your backup will start.
After that’s done, (backups are in sd:/gm9/out) in the GM9Megascript menu, go to Dump Options, then to Dump essential.exefs (it’s a few kilobytes).
Once you have both dumped you’ll be absolutely good to go with NAND backups! 
There’s also a Restore Backup option in the GM9Megascript. If you need it ever, you click on that, make sure you’re restoring the SysNAND, and it’ll restore your NAND from that backup.

**Comment by KeeveeKoomoo** [comment]
thanks for the suggestion but it didn't work. I'm really beginning to worry
it's a hardware issue. Is there any way to confirm or debunk that idea?

**Comment by KeeveeKoomoo** [comment]
also if I did have a nand backup, what would I lose buy restoring it?

**Comment by Mewthree3** [comment]
Ok so it’s most likely a hardware issue (maybe caused by old age/wear and tear on the system), but we can’t count out restoring a NAND backup could help?
So basically your saves for your 3DS games would be lost (cause they’re restored in the NAND). To be more accurate they’re reverting to the state they were left in when you did the backup last.
So if you want your saves up to date use Checkpoint to back all of them up (there might be a way to do all of them at once, but I’m not too sure), that’s the best way to do it.
Other system things (like the things that stay after your SD is removed, such as memos) will stay.
As for installed games you could need to install some of them again? Because I think tickets are saved on the system.
Either way give it a shot, (and maybe do a backup of your current one too, if you’d like)

**Comment by Masamune3210** [comment]
You should be able to use faketik to restore the tickets after a nand restore iirc

**Comment by Mewthree3** [comment]
Yeah use faketik to restore those tickets after those, thanks @Masamune3210 I knew there was some way to restore tickets!⚡️

**Comment by piepie62** [comment]
This is getting wildly offtopic. I'm locking it because of that; this is not a good place for general 3DS troubleshooting
