### ISSUE TITLE
Bug Report - PKSM shows wrong/old save of Pokemon Platinum in edit screen

### ISSUE THREAD

**Issue by flamelink527** [FlagBrew/PKSM#1306]
**Backstory and Bug**
For backstory: I have had an original copy of Pokemon Platinum since revision release.  After years, I deleted my save and started a new one.  Every time I load the new save it shows it is corrupt and I have to save several times to keep the current data. FYI, This was before I homebrewed my 3Ds.  When I loaded my game into pksm, it would show my old data from old save.  However, every backup save created from pksm, checkpoint, and twl show my new current yet corrupted save when loaded into an emulator.

**Settings and OS**
 - OS version: 3Ds 11.15.0-47U
 - PKSM version: v9.2.0-6

**Additional Info**
Someone I met in an emulation server managed to get the new save uncorrupted with a hex editor, but if possible I would like to be able to backup the old save.  I don't know if its possible but considering that pksm shows my old save when loaded vs the newer one, I would like to know.
![pksm homescreen](https://user-images.githubusercontent.com/93828467/140614159-f4b42d6f-df07-4231-b199-483945eef09f.jpg)
![new save](https://user-images.githubusercontent.com/93828467/140614177-063eda78-e234-465b-8c39-e31792ec9d4e.jpg)
![old save proof pksm](https://user-images.githubusercontent.com/93828467/140614180-d06b288b-3bb5-4682-804b-5a6518a89795.jpg)
![save corrupt](https://user-images.githubusercontent.com/93828467/140614301-bd6dab4f-3aa3-4f47-be14-6c83dac98c94.jpg)

**Comment by piepie62** [comment]
Platinum (and other Gen 4 games) contain two copies of the save, each taking up half of the save area. If you manually fixed your corrupted save dump, it's possible that you didn't update the save counts (which determine which save to load from the two) in the way PKSM expects. PKSM is a little more sensitive than the games themselves because it has to handle that logic for all three categories of G4 games, each of which has slightly different rules for save count interpretation. What seems likely is that one of the two save blocks in your current save has your new save, and the other has your old save. In order to back up a full save region with the old save active, you would have to edit the save counts such that the old one is the most recent (and passes the hash checks properly) according to the game's interpretation of save counts.

**Comment by flamelink527** [comment]
I see.  How would I do that in the sense of editing the save counts and stuff

**Comment by GriffinG1** [comment]
Out of context for here. I suggest going to ProjectPokemon's forums and asking there.
