### ISSUE TITLE
Returns me to home menu

### ISSUE THREAD

**Issue by DankCoffee** [FlagBrew/PKSM#1317]
**Bug Description**
When I open PKSM it says loading storage then it returns me to the home menu
**To Reproduce**
Latest version of pksm on my **updated** save
open pksm
its gonna crash when it says "Loading Storage"
**Expected behavior**
To backup my save data then update and launch normally

**Information about your environment**
 - OS version: [{CFW} 11.15.0-47 (Europe)]
 - PKSM version: 9.2.0

**Comment by GriffinG1** [comment]
So this is likely a result of you coming from an older version that allowed for a much larger bank size. You have two options available for fixing this:
1) Wait for @piepie62 to be available to manually fix your bank. He likely won't have access to a computer until early-mid August due to personal events.
2) You can delete your bank. I'll only recommend doing this if you have nothing in that bank, otherwise I strongly recommend waiting for Pie. If you'd prefer to do this please let me know and I'll tell you how.

**Comment by GriffinG1** [comment]
Hi. Following up on this as pie has PC access again, and need to know which option you would prefer. I will close this in a few days for inactivity if you don't reply.

**Comment by GriffinG1** [comment]
Closing due to continued inactivity since I first replied. Please join the FlagBrew discord server if you'd like further help with this.

**Comment by DankCoffee** [comment]
option 1

**Comment by GriffinG1** [comment]
@piepie62 all yours then, have fun
