### ISSUE TITLE
Bug Report - Specifically MY Pokémon don’t appear on GPSS

### ISSUE THREAD

**Issue by DampieNWC** [FlagBrew/PKSM#1363]
Uploading Pokémon to GPSS from PKHeX allows them to appear on the Flagbrew website, but not PKSM. It seems to only affect _my_ Pokémon

**To Reproduce**
1. Go to PKHeX
2. Click on any Pokémon
3. Then go to Tools, Auto-Legality Mod, GPSS Tools, and Upload to GPSS
4. See the Pokémon in GPSS on Flagbrew website, but not on PKSM’s GPSS

**Expected behavior**
My Pokémon appears at least on PKSM’s GPSS, as my specific intent is to bring a set of _legal_ Pokémon from my PC to my 3DS

**Screenshots**
![31A8DBC6-E241-41A4-892A-74410CF7D9C7](https://user-images.githubusercontent.com/108231483/224567318-f0fd7d78-58cc-44e6-8849-3f0c198a8eb0.jpeg)
![4D482426-4683-482F-89A0-CF24ECE23A7B](https://user-images.githubusercontent.com/108231483/224567319-fb5b7ffd-164e-453f-9474-3b30264f6ee8.jpeg)

**Information about your environment**
 - OS version: ?
 - PKSM version: v9.2.0-656eb68a
 - Entrypoint: ?

**Additional context**
I’m doing the newly-brought-to-light Foreverlocke (just look it up on YT if you don’t know what it is as I’m just gonna assume that you do) and this is my only way of bringing Gen 1-3 Pokémon to my 3DS.

**Comment by FM1337** [comment]
While not a PKSM issue per se, there will need to be a data structure change that will require an update to PKSM's handling of the returned JSON to ensure nothing breaks.

**Comment by FM1337** [comment]
I'm not going to close this ticket until the CoreAPI bug is resolved and an update is pushed to PKSM to ensure compatibility

**Comment by FM1337** [comment]
This issue should now be solved.

Due to API changes however, you will not be able to upload Pokemon to GPSS via PKHeX until https://github.com/architdate/PKHeX-Plugins/pull/192 is merged in and a new release of PKHeX-Plugins is released.

That being said, as I am 99% confident this is no longer an issue, I will be closing it. If the error does occur again after you are able to upload Pokemon to GPSS via PKHeX-Plugins again, then please re-open this issue.

Thank you.
