### ISSUE TITLE
sid

### ISSUE THREAD

**Issue by ryry007** [FlagBrew/PKSM#1389]
I have put in my tid alright but when I try to put in my sid it only allows 4 numbers and my sid is 5 numbers.

**Comment by GriffinG1** [comment]
You need to convert your TID/SID to G7 versions. `(SID << 16 | TID)` works I believe, where the first 4 digits of the result are your G7SID and the rest are your G7TID.

**Comment by ryry007** [comment]
so i need to convert to gen7 id version

**Comment by ryry007** [comment]
does it matter that i am on gen6?

**Comment by ryry007** [comment]
so if my sid was 28160 would the gen 7 id be 1845?

**Comment by ryry007** [comment]
> You need to convert your TID/SID to G7 versions. `(SID << 16 | TID)` works I believe, where the first 4 digits of the result are your G7SID and the rest are your G7TID. i dont understand what you mean by sid << 16 |TID

**Comment by piepie62** [comment]
For gen 6, you just need to input your TID and SID pair, converted to hexadecimal, into the provided four bytes, SID first. For gen 7+, there's a more complex formula. Converting a number to hexadecimal is a very simple operation you can look up easily. G7+ is a little tougher, in that the value you need to input into all four bytes of (SID * 1000000 + TID) converted to hexadecimal. I find it likely that you input your TID improperly, given your issue here.
