### ISSUE TITLE
Se Recibió una respuesta desconocida HTTP Error 0x000001F4

### ISSUE THREAD

**Issue by Amarillo3DS** [FlagBrew/PKSM#1402]
**No puedo verificar la legalidad o ilegalidad de mis Pokémon **

**Pasos para reproducir el error valla a cualquier Pokémon y viendo sus datos presiona Y para comprobar su legalidad*

**Comportamiento Previsto**
Que diga  si es o no legal

*Lo que sucede*
Da mensaje de error 

Captura no sé cómo se hace

**Comment by FM1337** [comment]
Sorry we cannot provide assistance in any language other than English. 

If you do require assistance, please open a new issue and fill out the form to the best of your ability using Google Translate (or have a translator localize your issue into English).

From the error code however, it appears a status of 500 was returned from the legalization service. This likely could be caused by a few things, but again, if you do require assistance please open a new issue and fill out the template.
