### ISSUE TITLE
Get all of a pokemon's basic abilities when spawning instead of the Pound attack

### ISSUE THREAD

**Issue by Floki1992** [FlagBrew/PKSM#1405]
**Is your feature request related to a problem? Please describe.**
Get all of a pokemon's basic abilities when spawning instead of the Pound attack

**Describe the solution you'd like**
When spawning any pokemon, the pokemon only knows the Pound attack, however, it would be nice if instead of the Pound attack, they default to the same abilities as if encountered in the  games.  I know that was the case until version 6

**Describe alternatives you've considered**

**Additional context**

**Comment by piepie62** [comment]
The way to do this would be to have full legality information based off of game data, which the 3DS can't handle, so this isn't going to happen.

**Comment by Floki1992** [comment]
@piepie62 Hello, how come this was the case before?

**Comment by piepie62** [comment]
I don't know exactly how that was implemented before; I wasn't part of the project before v6. However, I can tell you that it was game-context-unaware and thus not necessarily accurate, and by extension not necessarily legal, which leaves it at the same status as the Pound set right now, which I only leave there because a Pokémon with zero moves is invalid. I would honestly rather leave it empty, but that would leave invalid data in the game.
Regardless, this context-unawareness was okay back then because it only handled editing gen 6 and 7 games, but with 1-8 now, that becomes a major issue. However it worked then simply cannot now, it would need to be far more complex.
