### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by pokelector** [FlagBrew/PKSM#861]
Built-in legality checker?
When genderless Pokemon are made from scratch, make them automatically genderless.
G7 TID display.
TID and SID editing from editing menu.
Release button in Editor (add a check to make sure there's 1 Pokemon in the party)
Shiny sprites

**Comment by piepie62** [comment]
Alright, going down the list:
No, this has already been discussed at length
This is a pain to implement. Might add a way to set to genderless instead of just toggle genders.
Not sure what you mean
Maybe. Not a bad idea
No clue where to put it. I suppose it could be a physical button.
No, too much memory

**Comment by BernardoGiordano** [comment]
All the feasible feature requests in this issue have been implemented
