### ISSUE TITLE
Bank problem

### ISSUE THREAD

**Issue by KofiMatson123** [FlagBrew/PKSM#883]
Hey with the new update when I go to the bank it has only the first 150 pokemon in my banks. Even when I changed it to 2000 the older pokemon i placed past box 150 arent there anymore. Is there anyway of getting them back?

**Comment by sytantris** [comment]
@piepie62 thanks! I had made/restored with my own backup, but I did notice a bank.bin of the same size in that folder, which I realized later was probably the backup.

Okay, I can walk you through this @KofiMatson123 - at least how I did it, I'm using CFW/Luma/Homebrew. The tools might be different on other setups but the process is the same.

This is what I did; It worked fine for me, but I am not a project dev so all I can do is tell you my steps and the rationale involved - please be cautious and backup anything that might matter later! If anyone who is a PKSM dev can confirm this workflow that would be fantastic :)

**Godmode9: Move files around**
- First I entered Godmode9 by holding down `start` while turning my 3DS on.
- I had already made a backup directory in the SD root directory with my original `bank.bin` in it.
  - If you didn't back it up:
    - first create a backup directory, I recommend putting it in the root of the SD for easy access
    - then navigate to `/3ds/PKSM/backups/`
    - copy the `bank.bin` file and paste it into the backup directory you made (this will bring up a menu with two options, in this case I'd select copy instead of move)
    - now you have your own `bank.bin` backup, which is still in the PKSM directory, but this way it's easy to access.

Now, the next step was basically removing my PKSM directory to "start afresh" as it were. Doing this will force it to recreate the directory when it first runs again. This gives you something similar to a "fresh install" - but of course we back it up first to be safe. Note that this will clear any scripts or additional content you have downloaded, as well as the auto backups PKSM makes, but these are all things that can be re-downloaded or moved back after (I would ask one of the devs to go over this if you need to do it, because some files have changed places so I'm not really the best to advise on where these files belong - my main concern was getting my bank back, everything else was not important for me personally). Also, I personally like that doing this 'cleans up' the PKSM directory because otherwise it is left with files and folders from other versions that end up making it more confusing to troubleshoot. So:

- I navigated back to my `/3ds` directory and copied the entire `PKSM` folder.
- I then navigated back to my backup folder and pasted the copied `PKSM` folder into it (in this case, when the menu came up I chose the option to 'move' instead of 'copy')

Now navigating back to the `/3ds` folder there should no longer be a `PKSM` folder. It is safe in the backup folder. At this point, you could quit Godmode9 and run PKSM but I had a pretty good idea of how the backup process goes at this point so I just did everything in one sitting so as not to go back and forth. Basically it appears that PKSM checks for the existence of the `bank.bin` file in the `/bank` subfolder and if it exists, it copies it to the `/backups` folder and proceeds to convert the bank from there. So I wanted to recreate this folder structure before leaving Godmode9.

- Back in the `/3ds` folder, I created a new `PKSM` directory, and inside that, I created a `bank` directory.
- Navigating to my root backup folder, I copied `bank.bin` and pasted it in the `/3ds/PKSM/bank` directory I had just made (selecting copy, not move, this time - ensuring the backup is still saved).

At this point my SD card file structure looked like this (ignoring unrelated items):
- `/3ds`
  - `/PKSM`
    - `/bank`
      - `bank.bin`
- `/_backups`
  - `/PKSM` (and all of its subfolders)
  - `bank.bin`

If everything is in its place, it's time to quit Godmode9 and restart.

**PKSM: restore bank**
- Once my 3DS restarted I opened up PKSM.
- The very first thing I did was check my settings and ensured the storage size was set to the size of my previous storage (in my case, 1000). I imagine you can set it to larger than your previous storage if you want all 2000 boxes but you can also do that after. The important thing is that the storage size is set to the right amount and not 150 or whatever, which it will likely remember, but please double check and edit if necessary.
- At this point everything was prepared and it was time to see if it worked, so I exited the settings and went into storage. It re-ran the conversion (as I expected) and voila, I once again had 1000 boxes. I scrolled backwards into the mid-900s where I know I should have Pokemon and ... yay, there they were! My hand caught legendaries and events were safe and sound. Insert massive sigh of relief here.

So, that's what I did to restore my storage. I have no reason to think it wouldn't work for you but because I don't know your setup I don't want to say anything for sure, I'm just not an expert enough. But if you follow what I did carefully, you'll be backing everything up along the way anyway. Pay attention to details like capitalization with directory and file names, take it slow when inputting, double check things have ended up where you expected if you are at all unsure. (For all I know you know GM9 like the back of your hand and are super experienced, but I wanted to explain it as clearly as i could in case you, like me, are still figuring some of this CFW stuff out.

I hope this helps; feel free to poke me on the Discord (i'm SyDy) if you need any clarification.

There are probably ways in which this could be simplified but it requires more in depth knowledge of how the file structure is laid out than I personally have; perhaps one of the devs will be able to tighten up this process or has a better method entirely. I'm just saying this worked for me, and if I can help someone else who's dealing with what I just dealt with, I'd be happy about that :) Good luck and let us know how it works for you!

**Comment by KofiMatson123** [comment]
I just updated pksm went to my bank changed it to 2000 and they werent there past box 150

**Comment by piepie62** [comment]
Alright, made a fix for this. Once 6.0.2 comes out, move/copy `/3ds/PKSM/backups/bank.bin` to `/3ds/PKSM/bank/bank.bin` and it will import your full bank. Keep in mind that this will delete any changes you have made to your current bank, though
