### ISSUE TITLE
Geo loaction error with gen

### ISSUE THREAD

**Issue by krayziezay** [FlagBrew/PKSM#884]
Ok idk if its just my ds or if anyine else is having this problem. 
Os latest 11.9.0-42U
PKSM 6.0.1

Open PKSM and use US/UM
Gen Sandshrew lvl 1 
6iv
Scratch
Defense Curl
Save exit game run UM and try to trade and get error something wrong with pokemon.
Load PKHEX error is geolocation invalid. Country not a 3ds region.
Any ideas on a fix everything is US on my end.
My 3ds is US Washington DC
EmuNAND is 1 for Luma3DS v9.1
Is there anything on hex editor that I can use or change

**Comment by Pokefanmati** [comment]
Why didn't you fix it PKHEX since you used it?
How ever, try breeding two of that sandshrew using Destiny Knot and Everstone, you should get a complete legal flawless one in no time. 
I suggests this because PKSM staff says "We do not support or condone cheating at the expense of others. Do not use significantly edited Pokémon in battle or in trades with those who are unaware edited Pokémon are in use."

**Comment by krayziezay** [comment]
I did fix it in pkhex the reason why I was asking was because I gen on the go and trade to my cousin ds to whome Im not always around him. He knows that they are edited. I dont think there is any fix I can close this thread if need be

**Comment by krayziezay** [comment]
Figured it out
