### ISSUE TITLE
[Feature Request] ServePKX Support (again)

### ISSUE THREAD

**Issue by crzyc** [FlagBrew/PKSM#885]
Please add servepkx support again.

Or at least implement another way for PKSM to receive pk7 files over network. I know that there is a way for injecting pk7 files in the SD card, but not that I know of over network.

**Comment by InfiniteWorldLegacy** [comment]
Qucik question about that, during the weekend I have tried to use multiple previous versions of PKSM that supports servePKX, but for some weird reasons, they all show my boxes with graphic issues... plus, I even tried to use servepkx to send pk6 ans pk7 files, it always says that the pokemon were sent successfully, but in the app on my 3ds they didn't arrive... is that normal? 
i don't know why I had graphics issues and servepkx didn't work

**Comment by FM1337** [comment]
> Qucik question about that, during the weekend I have tried to use multiple previous versions of PKSM that supports servePKX, but for some weird reasons, they all show my boxes with graphic issues... plus, I even tried to use servepkx to send pk6 ans pk7 files, it always says that the pokemon were sent successfully, but in the app on my 3ds they didn't arrive... is that normal?
> i don't know why I had graphics issues and servepkx didn't work

Anything below the latest version of PKSM is no longer supported. The graphic issues are a result of it not being able to find the assets for the older versions of PKSM (this is intentional as these assets have been deleted and can no longer be downloaded)

As for why Servepkx didn't work, I'm not entirely sure, but no support for older versions will be given (other than explaining how to upgrade to the latest version, which is simple to do).

Servepkx support will be re-added in a future version of PKSM.

**Comment by BernardoGiordano** [comment]
Support has been added back, so this can be closed on PKSM's side of things
