### ISSUE TITLE
No PP MOVES  on pokemon 

### ISSUE THREAD

**Issue by B2bewild** [FlagBrew/PKSM#894]
Hey guys for some reason everytime I use pksm  to create or edit a pokemon,  they come out with no pp moves for example 
Ice beam 0/0.  Am I doing something wrong or is there a bug problem? It's on my Pearl game.  

Thank you

**Comment by B2bewild** [comment]
Yes.

**Comment by B2bewild** [comment]
An they come out fainted as well :/

**Comment by krayziezay** [comment]
I think for now you cannot gen via party or its gonna come out like that. To fix the problem either go to the pokecenter and heal or gen in the box and not the party

**Comment by piepie62** [comment]
Not exactly. That's just what happens right now; it should be fixed by recent commits and be included in 6.0.2

**Comment by B2bewild** [comment]
Hey guys 

Just wondering are you guys able to make the change of the nature easier then changing it through Pid,  like you click on it and it gives you the box of different natures it can had for example :
It comes as timid and you want to change it to adamant. Or is that not an option? 

Thank you

**Comment by SpiredMoth** [comment]
First, please don't ask questions in unrelated issues, especially if they've already been closed. We're less likely to see them when you do that.

Second, changing the nature in the way you describe is already the way it works in Gens 5-7. It's not implemented that way in Gen 4 because back then nature was controlled by the PID. To change Gen 4's behavior to work like the others would require rewriting the nature changing code to detect if the generation is 4 and then if it is to perform some complicated work on the PID to change the nature while making sure no [other details that are dependent on it](https://bulbapedia.bulbagarden.net/wiki/Personality_value#Usage) change.
