### ISSUE TITLE
Error during startup: 0xE0E046BE  (6.2.0)

### ISSUE THREAD

**Issue by relalien** [FlagBrew/PKSM#954]
**Describe the bug**
Every time I open PKSM I receive the same error, I've tried opening through the 3dsx file in homebrew and installing through FBI. Same issue.
I open it, see the homebrew splash screen, straight to black screen with version info at the top and the message. I do not use a flashcart, I'm trying this with legit carts if that makes any difference.

Error during startup: 0XE0E046BE

Description: Archive: init failed.

Press START to exit.

I press start and get moved to a crash dumb screen and have to shutdown my 3ds.
Everything is the latest version since I only started hacking my 3ds yesterday, everything else works fine.

**To Reproduce**
1. Open PKSM
2. See error

**Expected behavior**
Not sure because this is my first time opening it.

**Screenshots**
![IMG_20190327_143352248](https://user-images.githubusercontent.com/48975428/55049969-72a54780-509e-11e9-8566-338b1129f13c.jpg)
![IMG_20190327_144010624](https://user-images.githubusercontent.com/48975428/55049971-76d16500-509e-11e9-954e-d7d79d86a98c.jpg)
![IMG_20190327_144013833](https://user-images.githubusercontent.com/48975428/55049974-789b2880-509e-11e9-8b92-48cb21cb72f4.jpg)

**Information about your environment**
 - OS version: O3DS 11.9.9-42E
 - PKSM version: 6.2.0
 - Luma version: 9.1

**Comment by piepie62** [comment]
Can you try booting your 3DS, waiting 60 seconds, then opening PKSM? That seems to have solved the issue most of the time on the Discord server.

**Comment by relalien** [comment]
> Can you try booting your 3DS, waiting 60 seconds, then opening PKSM? That seems to have solved the issue most of the time on the Discord server.

The issue still persists even after waiting longer than that

**Comment by Mike007899** [comment]
Tips to resolve your issue with the latest error from v6.2.0:

1; reboot your 3DS from a coldboot and wait 30s-1m for the home menu to properly load, then open PKSM. (Make sure wifi is on as well.)

2; if 1 didnt help you, backup your extdata via checkpoint, delete it for PKSM via FBI, then reopen PKSM.

3; try updating manually/via QR instead of your normal approach.

4; if neither of those 3 tricks helped you, post here what all else you tried (if you downgraded, you will get NO help) and we can properly assist you.

Remember, without your help, this issue cannot be resolved. 

If you would like further assistance, meaning 1 on 1, join the discord.
https://discord.gg/bGKEyfY

**Comment by relalien** [comment]
Waiting didn't work, there was no extdata for PKSM because this was my first time using it, tried reinstalling via QR and Manually, neither worked

**Comment by Cordifhyura** [comment]
Same issue,first time installation
PS:Also force reboot when closing wireless micro sd transfer

**Comment by piepie62** [comment]
This has been fixed. New release coming soon.

**Comment by ruvy01** [comment]
Its back on the latest version, 7.0.1, same error

**Comment by piepie62** [comment]
Back up and immediately restore your PKSM ExtData with [Checkpoint](https://github.com/FlagBrew/Checkpoint/releases). If that doesn't work, join our [Discord server](https://discord.gg/bGKEyfY) and we'll troubleshoot from there

**Comment by ruvy01** [comment]
Perfect! Has to wait a bit for it to load but it worked! Thanks.
