### ISSUE TITLE
Feature Request: Edit Save Info

### ISSUE THREAD

**Issue by pokelector** [FlagBrew/PKSM#969]
Like PKHeX, it'd be nice if PKSM could edit your TID/SID/Trainer Name. Perhaps edit other things too like money, gender, BP, etc.

**Comment by piepie62** [comment]
No real point. TID, SID, trainer name, and gender edits will not be supported, and there's no point in not using the max money/BP scripts that are present. If you have something that there are not scripts for and/or seem difficult to do with scripts (though with PicoC scripts, basically anything is possible), feel free to mention them, but otherwise I don't think this is necessary.

**Comment by nycki93** [comment]
the point of this would be for transgender people who are returning to their old save files and want to fix their name. hope this helps!

**Comment by GriffinG1** [comment]
This was already implemented (as much as possible - gender for example, is too complex to change due to how it is integrated with flags, especially in later games) via an integrated script
